config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :orders
  resources :care_package_products
  resources :products
  resources :care_packages

  root 'pages#home'
end

app/models/care_package.rb
class CarePackage < ApplicationRecord
  has_many :care_package_products, dependent: :destroy
  has_many :products, through: :care_package_products

  has_many :order_items, dependent: :nullify
  has_many :orders, through: :order_items

  has_many_attached :images

  def update_price
    price = 0
    care_package_products.each do |care_package_product|
      price += care_package_product.product.price * care_package_product.quantity
    end
    update(price:)
  end
end

app/controllers/care_packages_controller.rb
class CarePackagesController < ApplicationController
  before_action :set_care_package, only: %i[ show edit update destroy ]

  # GET /care_packages or /care_packages.json
  def index
    @care_packages = CarePackage.all
  end

  # GET /care_packages/1 or /care_packages/1.json
  def show
  end

  # GET /care_packages/new
  def new
    @care_package = CarePackage.new
  end

  # GET /care_packages/1/edit
  def edit
  end

  # POST /care_packages or /care_packages.json
  def create
    @care_package = CarePackage.new(care_package_params)

    respond_to do |format|
      if @care_package.save
        format.html { redirect_to care_package_url(@care_package), notice: "Care package was successfully created." }
        format.json { render :show, status: :created, location: @care_package }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @care_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /care_packages/1 or /care_packages/1.json
  def update
    respond_to do |format|
      if @care_package.update(care_package_params)
        format.html { redirect_to care_package_url(@care_package), notice: "Care package was successfully updated." }
        format.json { render :show, status: :ok, location: @care_package }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @care_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /care_packages/1 or /care_packages/1.json
  def destroy
    @care_package.destroy

    respond_to do |format|
      format.html { redirect_to care_packages_url, notice: "Care package was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_care_package
      @care_package = CarePackage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def care_package_params
      params.require(:care_package).permit(:price)
    end
end

app/helpers/care_packages_helper.rb
module CarePackagesHelper
end

app/views/care_packages/_care_package.html.erb
<div id="<%= dom_id care_package %>">
  <p>
    <strong>Price:</strong>
    <%= care_package.price %>
  </p>

</div>

app/views/care_packages/_form.html.erb
<%= form_with(model: care_package) do |form| %>
  <% if care_package.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(care_package.errors.count, "error") %> prohibited this care_package from being saved:</h2>

      <ul>
        <% care_package.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/care_packages/edit.html.erb
<h1>Editing care package</h1>

<%= render "form", care_package: @care_package %>

<br>

<div>
  <%= link_to "Show this care package", @care_package %> |
  <%= link_to "Back to care packages", care_packages_path %>
</div>

app/views/care_packages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Care packages</h1>

<div id="care_packages">
  <% @care_packages.each do |care_package| %>
    <%= render care_package %>
    <p>
      <%= link_to "Show this care package", care_package %>
    </p>
  <% end %>
</div>

<%= link_to "New care package", new_care_package_path %>

app/views/care_packages/new.html.erb
<h1>New care package</h1>

<%= render "form", care_package: @care_package %>

<br>

<div>
  <%= link_to "Back to care packages", care_packages_path %>
</div>

app/views/care_packages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @care_package %>

<div>
  <%= link_to "Edit this care package", edit_care_package_path(@care_package) %> |
  <%= link_to "Back to care packages", care_packages_path %>

  <%= button_to "Destroy this care package", @care_package, method: :delete %>
</div>