config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :orders
  resources :care_package_products
  resources :products
  resources :care_packages

  root 'pages#home'
end

app/models/care_package_product.rb
class CarePackageProduct < ApplicationRecord
  belongs_to :care_package
  belongs_to :product

  after_save :update_care_package_prices

  def update_care_package_prices
    care_package.update_price
  end
end

app/controllers/care_package_products_controller.rb
class CarePackageProductsController < ApplicationController
  before_action :set_care_package_product, only: %i[ show edit update destroy ]

  # GET /care_package_products or /care_package_products.json
  def index
    @care_package_products = CarePackageProduct.all
  end

  # GET /care_package_products/1 or /care_package_products/1.json
  def show
  end

  # GET /care_package_products/new
  def new
    @care_package_product = CarePackageProduct.new
  end

  # GET /care_package_products/1/edit
  def edit
  end

  # POST /care_package_products or /care_package_products.json
  def create
    @care_package_product = CarePackageProduct.new(care_package_product_params)

    respond_to do |format|
      if @care_package_product.save
        format.html { redirect_to care_package_product_url(@care_package_product), notice: "Care package product was successfully created." }
        format.json { render :show, status: :created, location: @care_package_product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @care_package_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /care_package_products/1 or /care_package_products/1.json
  def update
    respond_to do |format|
      if @care_package_product.update(care_package_product_params)
        format.html { redirect_to care_package_product_url(@care_package_product), notice: "Care package product was successfully updated." }
        format.json { render :show, status: :ok, location: @care_package_product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @care_package_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /care_package_products/1 or /care_package_products/1.json
  def destroy
    @care_package_product.destroy

    respond_to do |format|
      format.html { redirect_to care_package_products_url, notice: "Care package product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_care_package_product
      @care_package_product = CarePackageProduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def care_package_product_params
      params.require(:care_package_product).permit(:care_package_id, :product_id, :quantity)
    end
end

app/helpers/care_package_products_helper.rb
module CarePackageProductsHelper
end

app/views/care_package_products/_care_package_product.html.erb
<div id="<%= dom_id care_package_product %>">
  <p>
    <strong>Care package:</strong>
    <%= care_package_product.care_package_id %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= care_package_product.product_id %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= care_package_product.quantity %>
  </p>

</div>

app/views/care_package_products/_form.html.erb
<%= form_with(model: care_package_product) do |form| %>
  <% if care_package_product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(care_package_product.errors.count, "error") %> prohibited this care_package_product from being saved:</h2>

      <ul>
        <% care_package_product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :care_package_id, style: "display: block" %>
    <%= form.text_field :care_package_id %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/care_package_products/edit.html.erb
<h1>Editing care package product</h1>

<%= render "form", care_package_product: @care_package_product %>

<br>

<div>
  <%= link_to "Show this care package product", @care_package_product %> |
  <%= link_to "Back to care package products", care_package_products_path %>
</div>

app/views/care_package_products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Care package products</h1>

<div id="care_package_products">
  <% @care_package_products.each do |care_package_product| %>
    <%= render care_package_product %>
    <p>
      <%= link_to "Show this care package product", care_package_product %>
    </p>
  <% end %>
</div>

<%= link_to "New care package product", new_care_package_product_path %>

app/views/care_package_products/new.html.erb
<h1>New care package product</h1>

<%= render "form", care_package_product: @care_package_product %>

<br>

<div>
  <%= link_to "Back to care package products", care_package_products_path %>
</div>

app/views/care_package_products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @care_package_product %>

<div>
  <%= link_to "Edit this care package product", edit_care_package_product_path(@care_package_product) %> |
  <%= link_to "Back to care package products", care_package_products_path %>

  <%= button_to "Destroy this care package product", @care_package_product, method: :delete %>
</div>